//! Parse `realm-workloads-launcher.json` and build the [`RealmGroup`] model.
//!
//! This module reads the static launcher metadata artifact generated by
//! `nixos-modules/realm-workloads-launcher-json.nix` and converts it into a
//! typed [`Vec<RealmGroup>`] suitable for the UI surfaces.
//!
//! Color resolution order (per realm):
//! 1. `ui-colors.json` → `envs[realm_name].accent` (realms often map 1:1 to
//!    envs during the v1→v2 migration).
//! 2. Hash-based derivation from the d2b palette — same deterministic
//!    algorithm as `ui-colors.nix` `colorForName`.
//!
//! Icon collision detection: if two or more workloads in the same realm share
//! the same icon string, each gets `has_icon_collision = true` and
//! `icon_siblings` lists the other action_ids.  The UI must show a chooser.

use std::collections::HashMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::config::UiColorArtifact;
use crate::model::{RealmGroup, RealmLauncherEntry};

// ---------------------------------------------------------------------------
// Wire types (realm-workloads-launcher.json)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LauncherArtifact {
    pub schema_version: String,
    pub workloads: Vec<LauncherWorkload>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct LauncherWorkload {
    pub realm_name: String,
    pub realm_id: String,
    pub workload_name: String,
    pub action_id: String,
    pub label: String,
    pub icon: String,
    pub canonical_target: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub legacy_vm_name: Option<String>,
}

// ---------------------------------------------------------------------------
// Color palette — mirrors ui-colors.nix colorPalette + colorForName
// ---------------------------------------------------------------------------

const COLOR_PALETTE: &[&str] = &[
    "#7fc8ff", "#90d090", "#ffb347", "#c8a0e0", "#ff8080", "#40e0d0", "#ffd700", "#ff69b4",
    "#a0c8a0", "#d4a0ff", "#ffa07a", "#87ceeb",
];

/// Derive an accent color from a name using the same deterministic hash as
/// `ui-colors.nix` `colorForName "d2b-env-accent"`.
fn color_for_name(name: &str) -> &'static str {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    // Mirror the Nix `builtins.hashString "sha256"` + substring + fromHexString
    // by using a stable Rust hash.  The exact palette index will differ from
    // the Nix-side derivation, but the palette is the same and the result is
    // visually consistent within wlcontrol (Nix-resolved colors come through
    // ui-colors.json when available anyway).
    let mut h = DefaultHasher::new();
    format!("d2b-env-accent-{name}").hash(&mut h);
    let idx = (h.finish() as usize) % COLOR_PALETTE.len();
    COLOR_PALETTE[idx]
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Load and parse `realm-workloads-launcher.json` from `path`.
///
/// Returns `Ok(vec![])` when the file is absent (not an error; the feature
/// is simply not configured).  Returns an error only for malformed JSON.
pub fn load_launcher_artifact(path: &Path) -> Result<Vec<LauncherWorkload>, String> {
    let text = match std::fs::read_to_string(path) {
        Ok(t) => t,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) if e.kind() == std::io::ErrorKind::PermissionDenied => {
            // Log and degrade gracefully; wlcontrol may run without d2bd-group ACL.
            eprintln!(
                "event=realm_launcher_error reason=permission_denied \
                 path_basename={} detail={e}",
                path.file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("realm-workloads-launcher.json")
            );
            return Ok(Vec::new());
        }
        Err(e) => {
            eprintln!(
                "event=realm_launcher_error reason=io \
                 path_basename={} detail={e}",
                path.file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("realm-workloads-launcher.json")
            );
            return Ok(Vec::new());
        }
    };
    let artifact: LauncherArtifact = serde_json::from_str(&text).map_err(|e| {
        format!(
            "malformed realm-workloads-launcher.json: {e} \
             (path={})",
            path.display()
        )
    })?;
    Ok(artifact.workloads)
}

/// Build the `Vec<RealmGroup>` model from loaded workloads and optional UI
/// color artifact (for realm accent resolution).
pub fn build_realm_groups(
    workloads: Vec<LauncherWorkload>,
    ui_colors: Option<&UiColorArtifact>,
) -> Vec<RealmGroup> {
    if workloads.is_empty() {
        return Vec::new();
    }

    // Group workloads by realm_name, preserving first-seen order.
    let mut realm_order: Vec<String> = Vec::new();
    let mut by_realm: HashMap<String, (String, Vec<LauncherWorkload>)> = HashMap::new();

    for wl in workloads {
        let rn = wl.realm_name.clone();
        let ri = wl.realm_id.clone();
        let entry = by_realm.entry(rn.clone()).or_insert_with(|| {
            realm_order.push(rn.clone());
            (ri, Vec::new())
        });
        entry.1.push(wl);
    }

    realm_order
        .into_iter()
        .map(|realm_name| {
            let (realm_id, realm_workloads) = by_realm.remove(&realm_name).unwrap();

            // Resolve realm accent color.
            let realm_color = resolve_realm_color(&realm_name, ui_colors);

            // Detect icon collisions within this realm.
            let entries = build_entries_with_collisions(realm_workloads);

            RealmGroup {
                realm_name,
                realm_id,
                realm_color,
                workloads: entries,
            }
        })
        .collect()
}

fn resolve_realm_color(realm_name: &str, ui_colors: Option<&UiColorArtifact>) -> String {
    if let Some(colors) = ui_colors {
        if let Some(realm_color) = colors.realms.get(realm_name) {
            return realm_color.accent.clone();
        }
        if let Some(env_color) = colors.envs.get(realm_name) {
            return env_color.accent.clone();
        }
    }
    color_for_name(realm_name).to_owned()
}

fn build_entries_with_collisions(workloads: Vec<LauncherWorkload>) -> Vec<RealmLauncherEntry> {
    // Build icon → [action_id, ...] map to detect collisions.
    let mut icon_to_ids: HashMap<String, Vec<String>> = HashMap::new();
    for wl in &workloads {
        icon_to_ids
            .entry(wl.icon.clone())
            .or_default()
            .push(wl.action_id.clone());
    }

    workloads
        .into_iter()
        .map(|wl| {
            let siblings = icon_to_ids.get(&wl.icon).cloned().unwrap_or_default();
            let has_collision = siblings.len() > 1;
            let icon_siblings: Vec<String> = if has_collision {
                siblings
                    .into_iter()
                    .filter(|id| id != &wl.action_id)
                    .collect()
            } else {
                Vec::new()
            };
            RealmLauncherEntry {
                action_id: wl.action_id,
                workload_name: wl.workload_name,
                label: wl.label,
                icon: wl.icon,
                canonical_target: wl.canonical_target,
                legacy_vm_name: wl.legacy_vm_name,
                has_icon_collision: has_collision,
                icon_siblings,
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{UiColorEnv, UiColorHost, UiColorRealm, UiColorStates};
    use std::collections::BTreeMap;

    fn workload(
        realm_name: &str,
        realm_id: &str,
        workload_name: &str,
        icon: &str,
    ) -> LauncherWorkload {
        LauncherWorkload {
            realm_name: realm_name.to_owned(),
            realm_id: realm_id.to_owned(),
            workload_name: workload_name.to_owned(),
            action_id: workload_name.to_owned(),
            label: workload_name.to_owned(),
            icon: icon.to_owned(),
            canonical_target: format!("{workload_name}.{realm_name}.d2b"),
            legacy_vm_name: Some(workload_name.to_owned()),
        }
    }

    fn ui_colors_with_env(env: &str, accent: &str) -> UiColorArtifact {
        let mut envs = BTreeMap::new();
        envs.insert(
            env.to_owned(),
            UiColorEnv {
                accent: accent.to_owned(),
            },
        );
        UiColorArtifact {
            version: 1,
            host: UiColorHost {
                accent: "#7fc8ff".to_owned(),
            },
            states: UiColorStates {
                running: "#a6e3a1".to_owned(),
                transitioning: "#f9e2af".to_owned(),
                pending_restart: "#fab387".to_owned(),
                error: "#f38ba8".to_owned(),
                denied: "#cba6f7".to_owned(),
                unknown: "#6c7086".to_owned(),
            },
            envs,
            realms: BTreeMap::new(),
            vms: BTreeMap::new(),
        }
    }

    fn ui_colors_with_realm_and_env(
        realm: &str,
        realm_accent: &str,
        env_accent: &str,
    ) -> UiColorArtifact {
        let mut colors = ui_colors_with_env(realm, env_accent);
        colors.realms.insert(
            realm.to_owned(),
            UiColorRealm {
                accent: realm_accent.to_owned(),
                path: realm.to_owned(),
            },
        );
        colors
    }

    #[test]
    fn empty_workloads_yields_empty_groups() {
        assert!(build_realm_groups(vec![], None).is_empty());
    }

    #[test]
    fn groups_workloads_by_realm() {
        let wls = vec![
            workload("work", "work", "browser", "web"),
            workload("work", "work", "terminal", "terminal"),
            workload("personal", "personal", "music", "music_note"),
        ];
        let groups = build_realm_groups(wls, None);
        assert_eq!(groups.len(), 2);
        assert_eq!(groups[0].realm_name, "work");
        assert_eq!(groups[0].workloads.len(), 2);
        assert_eq!(groups[1].realm_name, "personal");
        assert_eq!(groups[1].workloads.len(), 1);
    }

    #[test]
    fn uses_env_accent_color_from_ui_colors() {
        let wls = vec![workload("work", "work", "browser", "web")];
        let colors = ui_colors_with_env("work", "#ff8000");
        let groups = build_realm_groups(wls, Some(&colors));
        assert_eq!(groups[0].realm_color, "#ff8000");
    }

    #[test]
    fn prefers_realm_accent_color_from_ui_colors() {
        let wls = vec![workload("work", "work", "browser", "web")];
        let colors = ui_colors_with_realm_and_env("work", "#ffb347", "#ffa500");
        let groups = build_realm_groups(wls, Some(&colors));
        assert_eq!(groups[0].realm_color, "#ffb347");
    }

    #[test]
    fn falls_back_to_palette_hash_when_env_absent() {
        let wls = vec![workload("personal", "personal", "music", "music_note")];
        let colors = ui_colors_with_env("work", "#ff8000");
        let groups = build_realm_groups(wls, Some(&colors));
        // Should be a valid palette color, not "#ff8000".
        assert!(
            COLOR_PALETTE.contains(&groups[0].realm_color.as_str()),
            "expected palette color, got {}",
            groups[0].realm_color
        );
    }

    #[test]
    fn detects_icon_collisions_within_realm() {
        // "browser" and "mail" both use icon "web" in the same realm.
        let wls = vec![
            workload("work", "work", "browser", "web"),
            workload("work", "work", "mail", "web"),
            workload("work", "work", "terminal", "terminal"),
        ];
        let groups = build_realm_groups(wls, None);
        let entries = &groups[0].workloads;

        let browser = entries.iter().find(|e| e.action_id == "browser").unwrap();
        let mail = entries.iter().find(|e| e.action_id == "mail").unwrap();
        let term = entries.iter().find(|e| e.action_id == "terminal").unwrap();

        assert!(browser.has_icon_collision);
        assert_eq!(browser.icon_siblings, vec!["mail"]);
        assert!(mail.has_icon_collision);
        assert_eq!(mail.icon_siblings, vec!["browser"]);
        assert!(!term.has_icon_collision);
        assert!(term.icon_siblings.is_empty());
    }

    #[test]
    fn no_collision_for_unique_icons() {
        let wls = vec![
            workload("work", "work", "browser", "web"),
            workload("work", "work", "terminal", "terminal"),
        ];
        let groups = build_realm_groups(wls, None);
        assert!(groups[0].workloads.iter().all(|e| !e.has_icon_collision));
    }

    #[test]
    fn cross_realm_icons_do_not_collide() {
        // Same icon "web" appears in both "work" and "personal" — no collision.
        let wls = vec![
            workload("work", "work", "corp-browser", "web"),
            workload("personal", "personal", "browser", "web"),
        ];
        let groups = build_realm_groups(wls, None);
        for group in &groups {
            for entry in &group.workloads {
                assert!(
                    !entry.has_icon_collision,
                    "unexpected collision for {} in {}",
                    entry.action_id, group.realm_name
                );
            }
        }
    }

    #[test]
    fn preserves_realm_insertion_order() {
        let wls = vec![
            workload("personal", "personal", "music", "music_note"),
            workload("work", "work", "browser", "web"),
        ];
        let groups = build_realm_groups(wls, None);
        assert_eq!(groups[0].realm_name, "personal");
        assert_eq!(groups[1].realm_name, "work");
    }

    #[test]
    fn parse_artifact_json() {
        let json = r#"{
            "schemaVersion": "v1",
            "runtimeState": "metadata-only",
            "invariants": {},
            "workloads": [
                {
                    "realmName": "work",
                    "realmId": "work",
                    "realmPath": "work.corp.d2b",
                    "workloadName": "corp-browser",
                    "actionId": "corp-browser",
                    "label": "Corp Browser",
                    "icon": "web",
                    "canonicalTarget": "corp-browser.work.corp.d2b",
                    "capabilityRefs": [],
                    "appCommand": null,
                    "actions": [],
                    "legacyVmName": "corp-browser",
                    "substrateId": "corp-browser",
                    "runtimeKind": "nixos",
                    "runtimeProviderId": "cloud-hypervisor",
                    "targetAddress": "corp-browser.work.corp.d2b",
                    "vsockCid": null
                }
            ]
        }"#;
        let artifact: LauncherArtifact = serde_json::from_str(json).expect("parse");
        assert_eq!(artifact.workloads.len(), 1);
        assert_eq!(artifact.workloads[0].realm_name, "work");
        assert_eq!(artifact.workloads[0].icon, "web");
    }
}
